# Generated by Django 3.1.4 on 2021-01-02 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0008_auto_20210102_0636'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
