# Generated by Django 3.1.4 on 2021-01-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0013_auto_20210111_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
