# Generated by Django 3.1.4 on 2021-01-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0014_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='О себе'),
        ),
    ]
